# Article information
## Article title
The article title must include the word ‘data’ or ‘dataset’. 

Dataset of on-camera and off-camera occurrence records of mammals and birds in the Gran Sabana, Venezuela

## Authors
Please list all authors (first name(s) - last name) and mark the corresponding author with *.
Izabela Stachowicz
JR Ferrer-Paris *


## Affiliations
Please include the full postal address of each author’s institution.



## Corresponding author’s email address and Twitter handle
Please use your institutional email address. If you have one, please also add your Twitter handle here.

## Keywords
Include 4-8 keywords, separated by semi-colons. Please do not repeat words used in your title.


## Abstract
The abstract should be 100 to 500 words long and describe the data collection process, the dataset, and its reuse potential. It should not provide conclusions or interpretations.


# SPECIFICATIONS TABLE
### Subject
Please select a subject area from the list available at DIB categories.
### Specific subject area
Briefly describe the specific subject area. Max 150 characters (without spaces).
### Data format
Please list your data format(s). Delete any descriptions from the list that do not apply. If your data format is not featured, please manually add it.  
Raw, Analyzed, Filtered
### Type of data
Please list your type(s) of data. Delete any description from the list that does not apply. If your data type is not featured, please manually add it.
Table, Image, Chart, Graph, Figure
### Data collection
Briefly describe how the data were collected. Please provide information on instruments you used (e.g., microscope, mass spectrometry, specific hardware or software etc., including relevant make/model details) as well as on methods used for collecting data or inclusion/exclusion criteria. You may also describe how the data were normalized. In case of questionnaires, please briefly describe the sources used to derive the question items. Max 600 characters (without spaces).
### Data source location
Please mention where the data were collected (e.g.  geographical coordinates) or where the data are stored (typically your affiliation).
### Data accessibility
Please note: All raw data referred to in this article must be made publicly available in a data repository prior to publication. Please indicate here where your data are hosted (the URL must be working at the time of submission and editors and reviewers must have anonymous access to the repository): 
Repository name: Figshare
Data identification number: 10.6084/m9.figshare.21174589
Direct URL to data: https://figshare.com/articles/dataset/Camera_trap_data_and_spatial_covariates_for_monitoring_vertebrates_in_the_Gran_Sabana_Venezuela/21174589

Instructions for accessing these data:


### Related research article
If your manuscript supports a related research article, please cite this article here. If your manuscript is not related to a research article, please delete this entire row. You should list only one article here. Please upload a copy of your related research article to your submission.



# VALUE OF THE DATA
This section states why these data are of value to the scientific community and provides your reasoning and context behind the generation of this dataset. Please provide between 3 and 6 bullet points, and answer at least the questions below (delete the questions afterwards). Each bullet point should be a maximum of 100 words long, and should not include conclusions or inferences:
    • Why are these data valuable?
    • Who can benefit from these data?
    • How can these data be reused by other researchers?
    
# DATA DESCRIPTION
This section describes your dataset. Refer to all the data folders, subfolders, and files in the repository individually, irrespective of whether they relate to raw or analyzed data, and make sure that the reader can follow the structure of your dataset.
Please use visual aids (such as tables, graphs, or figures with captions) to familiarize the reader with your dataset, but do not offer background, interpretations, or conclusions.


# EXPERIMENTAL DESIGN, MATERIALS AND METHODS
This section describes how you acquired the data. Provide a complete description of the experimental design and methods used to acquire these data. For example, include all code (files) and software used for data analysis or data generation, and describe tools, instruments, and experimental conditions. 
It is important that this section is as comprehensive as possible. There is no character limit, and you may use illustrative figures or tables; however, please do not offer background, interpretations, or conclusions.


# LIMITATIONS
Describe any limitations related to the data described in this article. These could be any problems you faced during data collection or curation, limited quality or size of dataset, data biases, etc., but should not include limitations of analysis conducted or interpretation (Max. 200 words).
If there are none, please write ‘None’ or ‘Not applicable’.

# ETHICS STATEMENT
Data in Brief’s Guide for Authors contains detailed information on the ethical guidelines with which all authors must comply. In addition, we ask you to complete the relevant statement(s) below.  Please delete those which are not relevant for your data.
 If your work involved human subjects, please include a statement here confirming that the relevant informed consent was obtained from those subjects, if the research was carried out in accordance with the Declaration of Helsinki, and if it includes the Ethical committee approval and the protocol number. A copy of the consent form (in English) can be submitted either in a data repository or under the section ‘Consent form’ while submitting the manuscript to the system.
If your work involved animal experiments, please include a statement here confirming that those experiments complied with the ARRIVE guidelines and were carried out in accordance with the U.K. Animals (Scientific Procedures) Act, 1986 and associated guidelines; EU Directive 2010/63/EU for animal experiments; or the National Institutes of Health guide for the care and use of laboratory animals (NIH Publications No. 8023, revised 1978). Note, the sex of the animals must be indicated, and, where appropriate, the influence (or association) of sex on the results of the study.
 If your work involved data collected from social media platforms, please include a statement here confirming that a) informed consent was obtained from participants or that participant data has been fully anonymized, and b) the platform(s)’ data redistribution policies were complied with.
If none of the above, please include a statement confirming that the authors have read and follow the ethical requirements for publication in Data in Brief and confirming that the current work does not involve human subjects, animal experiments, or any data collected from social media platforms.

The following information was supplied relating to ethical approvals (i.e., approving body
and any reference numbers):
The study received permits from Instituto Nacional de Parques (INPARQUES) 18/16
205, 156, 17 in Venezuela and local authority in Gran Sabana that authorize human
participation in surveys.
Additionally, local indigenous authorities from sector 5 in Gran Sabana gave
authorization to carry out the project that includes camera trapping and interviews.

# CRediT AUTHOR STATEMENT
Please outline the contributions of each co-author, using the categories listed on this webpage.

Izabela Stachowicz conceived and designed the experiments, performed the experiments,
analyzed the data, prepared figures and/or tables, authored or reviewed drafts of the
paper, and approved the final draft.
José R Ferrer-Paris conceived and designed the experiments, analyzed the data, prepared
figures and/or tables, authored or reviewed drafts of the paper, and approved the final
draft.

# ACKNOWLEDGEMENTS
In this section, mention all contributors who do not meet the criteria for authorship. 
In addition, please list any funding sources in this section. List funding sources in the standard way to facilitate compliance to funder's requirements.
If no funding has been provided for the research, please include the following sentence:
This research did not receive any specific grant from funding agencies in the public, commercial, or not-for-profit sectors.
Idea Wild foundation and Finca Dos Aguas from Venezuela.This work was supported by Idea Wild foundation and Finca Dos Aguas from Venezuela.
The funders had no role in study design, data collection and analysis, decision to publish,
or preparation of the manuscript.

# DECLARATION OF COMPETING INTERESTS
Please choose one appropriate statement from below and delete the one that does not apply (if applicable, please specify the nature of your competing interests). 
    • The authors declare that they have no known competing financial interests or personal relationships that could have appeared to influence the work reported in this paper.

# REFERENCES
In this section, please provide a numbered list of references. References are limited to a maximum of 20 and irrelevant self-citation is not allowed.  
Please format all in-text citations by number(s) in square brackets in line with the text. The actual authors can be referred to, but the reference number(s) must always be given.
IMPORTANT: If your data article supports an original research article, please cite the associated article here; ideally, it should be the first citation. 
Please also make sure to cite your dataset in the data repository.

1.

2. Ferrer-Paris, José R.; Stachowicz, Izabela (2022). Camera trap data and spatial covariates for monitoring vertebrates in the Gran Sabana, Venezuela. figshare. Dataset. https://doi.org/10.6084/m9.figshare.21174589.v1
